### ISSUE TITLE
Option to use the Email instead of username for Webex Link

### ISSUE THREAD

**Issue by stefancyliax** [wreiske/Rocket.Chat.App-WebEx#2]
Hey,
Currently the plugin uses the username for the last part of the Webex link.
An Option to be able to use the email-address of a user (without the @) would be great. This is what we are using for Webex Links.

example:
EMail: Firstname.Lastname@Company.com
Webex Link:
https://domain.webex.com/join/Firstname.LastnameCompany.com 

Thanks and with kind regards
Stefan

**Comment by wreiske** [comment]
In the meantime, you can always type `/webex Firstname.LastnameCompany.com` and it should work. 
I may be able to add some kind of configurable option for the WebEx URL...

I'm thinking something like:

**URL:** {username}

or 

**URL:** {first_name}.{last_name}Company.com

or

**URL:** {email}

{email} would strip the @ from the URL. 

What do you think of that?

**Comment by stefancyliax** [comment]
Does Rocketchat have variables for first_name and last_name?
For my application the {email} would be sufficient (@ stripping needed).

Thanks and kind regards

**Comment by stefancyliax** [comment]
This is no longer needed from my side. We went onto other solutions.
