### ISSUE TITLE
Permission Denied on Rocket v.3.15

### ISSUE THREAD

**Issue by alvarow** [wreiske/Rocket.Chat.App-WebEx#21]
Hello, since upgrading Rocket to v3.15.0 the app no longer works with the error message "Not enough permission", and I see this on the logs:

```
server.js:204 System ➔ error Error sending message: Error: Not enough permission     at validateMessage (app/lib/server/functions/sendMessage.js:151:10)     at sendMessage (app/lib/server/functions/sendMessage.js:165:2)     at executeSendMessage (app/lib/server/methods/sendMessage.js:78:10)     at app/apps/server/bridges/messages.js:17:23     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
```

Any ideas?

Thanks

**Comment by wreiske** [comment]
Rocket.Chat added an impersonation permission to their roles. If you go to roles and look for "user", add the impersonate permission and it should work!

**Comment by alvarow** [comment]
thanks that did! Now I am left wondering what nefarious effects it will have from allowing users to impersonate others!
